# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 151, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 80, 151, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 191, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 30, 151, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 80, 151, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 160, 151, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 220, 151, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 10, 561, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 30, 251, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 60, 251, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 90, 251, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 120, 251, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 150, 251, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 180, 251, 19))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_8.setGeometry(QtCore.QRect(290, 30, 251, 19))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_9.setGeometry(QtCore.QRect(290, 60, 251, 19))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_10.setGeometry(QtCore.QRect(290, 90, 251, 19))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_11.setGeometry(QtCore.QRect(290, 120, 251, 19))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_12.setGeometry(QtCore.QRect(290, 150, 251, 19))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_13.setGeometry(QtCore.QRect(290, 180, 251, 19))
        self.checkBox_13.setObjectName("checkBox_13")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 230, 561, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_20.setGeometry(QtCore.QRect(380, 20, 151, 40))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(200, 20, 151, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(10, 310, 761, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(520, 10, 251, 241))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox.setGeometry(QtCore.QRect(10, 120, 221, 19))
        self.checkBox.setObjectName("checkBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 221, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 221, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 90, 221, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 491, 241))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(50, 60, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 260, 761, 241))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 80, 221, 40))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 180, 221, 40))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 130, 221, 40))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 161, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_29.setGeometry(QtCore.QRect(180, 30, 51, 40))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_25.setGeometry(QtCore.QRect(260, 30, 221, 40))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_26.setGeometry(QtCore.QRect(260, 80, 221, 40))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_27.setGeometry(QtCore.QRect(260, 130, 221, 40))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_28.setGeometry(QtCore.QRect(260, 180, 221, 40))
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "afk-arena-tools V1.1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "主线模式"))
        self.pushButton.setText(_translate("MainWindow", "自动重试"))
        self.pushButton_2.setText(_translate("MainWindow", "自动推图"))
        self.groupBox_2.setTitle(_translate("MainWindow", "王座之塔模式"))
        self.pushButton_5.setText(_translate("MainWindow", "自动重试"))
        self.pushButton_6.setText(_translate("MainWindow", "自动推图"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_3.setTitle(_translate("MainWindow", "每日任务"))
        self.checkBox_2.setText(_translate("MainWindow", "挑战首领1次（20pts）"))
        self.checkBox_3.setText(_translate("MainWindow", "领取战利品2次（10pts）"))
        self.checkBox_4.setText(_translate("MainWindow", "赠送好友友情点1次（10pts）"))
        self.checkBox_5.setText(_translate("MainWindow", "快速挂机1次（10pts）"))
        self.checkBox_6.setText(_translate("MainWindow", "在月桂酒馆召唤英雄1次（20pts）"))
        self.checkBox_7.setText(_translate("MainWindow", "参加公会团队狩猎1次（10pts）"))
        self.checkBox_8.setText(_translate("MainWindow", "参加竞技场挑战1次（20pts）"))
        self.checkBox_9.setText(_translate("MainWindow", "接受3个悬赏任务（10pts）"))
        self.checkBox_10.setText(_translate("MainWindow", "挑战王座之塔1次（10pts）"))
        self.checkBox_11.setText(_translate("MainWindow", "Placeholder"))
        self.checkBox_12.setText(_translate("MainWindow", "Placeholder"))
        self.checkBox_13.setText(_translate("MainWindow", "Placeholder"))
        self.groupBox_4.setTitle(_translate("MainWindow", "流程控制"))
        self.pushButton_20.setText(_translate("MainWindow", "停止"))
        self.pushButton_9.setText(_translate("MainWindow", "开始每日任务"))
        self.pushButton_10.setText(_translate("MainWindow", "没用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "功能区"))
        self.groupBox_7.setTitle(_translate("MainWindow", "分辨率设置"))
        self.checkBox.setText(_translate("MainWindow", "使用720/1080的比例"))
        self.radioButton.setText(_translate("MainWindow", "1440P / 2K (1440x2560)"))
        self.radioButton_2.setText(_translate("MainWindow", "1080P (1080x1920)"))
        self.radioButton_3.setText(_translate("MainWindow", "720P (720x1280)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "配置文件设置"))
        self.label.setText(_translate("MainWindow", "啥也没有"))
        self.groupBox_5.setTitle(_translate("MainWindow", "ADB功能区"))
        self.pushButton_21.setText(_translate("MainWindow", "WIFI连接手机"))
        self.pushButton_22.setText(_translate("MainWindow", "获取截图（弹窗）"))
        self.pushButton_23.setText(_translate("MainWindow", "运行adb devices"))
        self.pushButton_29.setText(_translate("MainWindow", "保存"))
        self.pushButton_25.setText(_translate("MainWindow", "保存截图"))
        self.pushButton_26.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_27.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_28.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "设置"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.action.setText(_translate("MainWindow", "afk-arena-tools 帮助"))
        self.action_2.setText(_translate("MainWindow", "关于"))
